Test
jaceklaskowski/scalania pull request #49
Opened 2017-09-28 11:42 UTC by khanfaizan1

2017-09-28 11:49 UTC, jaceklaskowski requested changes
1. Does `JenkinsFile` have to be in the main directory?

2017-09-28 11:49 UTC, jaceklaskowski commented on README.md
> +# [Scalania] (http://scalania.pl) - Learn Scala by Examples,,,,,,,,,,,
Why so many commas?

2017-09-28 11:49 UTC, jaceklaskowski commented on dsfasfd
> +node {
Is the file valid? The file name suggests the opposite.

2017-09-29 06:58 UTC, khanfaizan1 commented
Sorry I am new to Github and was just testing Jenkins Webhooks,

On Thu, Sep 28, 2017 at 4:49 PM, Jacek Laskowski <notifications@github.com>
wrote:

> *@jaceklaskowski* requested changes on this pull request.
>
>    1. Does JenkinsFile have to be in the main directory?
>
> ------------------------------
>
> In README.md
> <https://github.com/jaceklaskowski/scalania/pull/49#discussion_r141595378>
> :
>
> > @@ -1,4 +1,4 @@
> -# [Scalania](http://scalania.pl) - learn Scala by examples
> +# [Scalania] (http://scalania.pl) - Learn Scala by Examples,,,,,,,,,,,
>
> Why so many commas?
> ------------------------------
>
> In dsfasfd
> <https://github.com/jaceklaskowski/scalania/pull/49#discussion_r141595484>
> :
>
> > @@ -0,0 +1,30 @@
> +node {
>
> Is the file valid? The file name suggests the opposite.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaceklaskowski/scalania/pull/49#pullrequestreview-65832343>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVmw9SXa9DSH87WYESNkdw57cXQvCPcaks5sm4e3gaJpZM4PnIrK>
> .
>

2017-10-01 12:39 UTC, jaceklaskowski requested changes

2017-10-01 12:39 UTC, jaceklaskowski commented on README.md
> +# [Scalania] (http://scalania.pl) - Learn Scala by Examples,,
Why two commas at the end?

2017-10-06 06:20 UTC, khanfaizan1 commented
Can one of the admins verify this patch?

2018-03-29 10:02 UTC, jaceklaskowski commented
Closing the pull request as it was inactive for some time.

2018-03-29 10:02 UTC, closed without merging